name: Swift Release Binaries

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-13
    strategy:
      matrix:
        arch: [x86_64, arm64] # macOS architectures
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Select Xcode version
        run: sudo xcode-select --switch /Applications/Xcode_14.3.1.app

      - name: Build Swift application
        run: |
          chmod +x build.sh
          commit=$(git rev-parse --short HEAD)
          export VERSION="${{ github.ref_name }}-$commit"
          export ARCH="${{ matrix.arch }}"
          ./build.sh

      - name: Package binary for release
        run: |
          mkdir -p release
          cp logpopup-${{ matrix.arch }} release/logpopup-${{ matrix.arch }}

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: logpopup-${{ matrix.arch }}
          path: release/logpopup-${{ matrix.arch }}
          retention-days: 1

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: binaries/
          merge-multiple: true

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          draft: true
          generate_release_notes: true
          files: binaries/*